name = "castle-service"
main = "src/worker.ts"
compatibility_date = "2024-09-15"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 4001

# Default production environment
[env.production]
name = "castle-service"
vars = { ENVIRONMENT = "production" }

# Staging environment
[env.staging]
name = "castle-service-staging"
vars = { ENVIRONMENT = "staging" }

# Development environment
[env.development]
name = "castle-service-dev"
vars = { ENVIRONMENT = "development" }


# KV storage (if needed for caching)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Secrets (set via wrangler secret put)
# ENTENTE_API_KEY